import Head from "next/head";
import Scene from "../components/Scene";
import Overlay from "../components/Overlay";
import { useState } from "react";

export default function Home() {
  const [action, setAction] = useState("home");

  return (
    <div>
      <Head>
        <title>garrett.cool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Scene action={action} setAction={setAction} />
      </div>
      <Overlay action={action} setAction={setAction} />
    </div>
  );
}
