import Head from "next/head";
import Scene from "../components/Scene";
import Overlay from "../components/Overlay";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Scene />
      <Overlay />
    </div>
  );
}
